spring:
  profiles: test
config:
  name: test
  environment: test
application:
  ratelimit:
    global: 0

---
spring:
  profiles: prod
config:
  name: prod
  environment: production
beans:
  widgetservice:
    impl: WidgetSqlService
application:
  ratelimit:
    global: 1000
    endpoints:
      -
        method: GET
        path: /widgets
        limit: 100
        params:
          - page
          - size
      -
        method: POST
        path: /widgets
        limit: 10